jco.destination.pool_capacity=0
jco.client.lang=en
jco.client.sysnr=00
jco.destination.peak_limit=10
CONFIGURED_USER=10


log.path=log
system.config.path=../SystemConfig.csv
#system.config.path=D:\\Rajesh\\Moh\\BH\\javaApp_ubuntu\\javaApp_ubuntu\\SystemConfig.csv

# Springdoc OpenAPI / Swagger UI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.doc-expansion=list
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


